id: Active Directory - ad-get-user limit check
version: 39
contentitemexportablefields:
  contentitemfields:
    packID: ""
    itemVersion: 1.0.1
    fromServerVersion: ""
    toServerVersion: ""
vcShouldKeepItemLegacyProdMachine: false
name: Active Directory - ad-get-user limit check
description: Checked the limit in ad-get-user command, in cas no limit was added the default is 200.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6a43d401-b2d1-4298-86a3-44b9865ff630
    type: start
    task:
      id: 6a43d401-b2d1-4298-86a3-44b9865ff630
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 440,
          "y": -380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: ae48bd06-6360-4327-8bf7-9b8ed0ab59c2
    type: condition
    task:
      id: ae48bd06-6360-4327-8bf7-9b8ed0ab59c2
      version: -1
      name: Is Active Directory enabled?
      description: Checks if the Active Directory Query v2 integration is enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "12"
      "yes":
      - "19"
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: brand
                      iscontext: true
                    right:
                      value:
                        simple: Active Directory Query v2
                - - operator: isEqualString
                    left:
                      value:
                        simple: state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 440,
          "y": -60
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: bdcb3cc0-6dcb-4192-8827-9d6310a812d4
    type: title
    task:
      id: bdcb3cc0-6dcb-4192-8827-9d6310a812d4
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 850
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: e94bf31d-7369-42a7-818a-8f41354438fc
    type: regular
    task:
      id: e94bf31d-7369-42a7-818a-8f41354438fc
      version: -1
      name: Run ad-get-user with no limit
      description: Retrieves detailed information about a user account. The user can
        be specified by name, email address, or as an Active Directory Distinguished
        Name (DN). If no filter is specified, all users are returned.
      script: '|||ad-get-user'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      attributes: {}
      custom-field-data: {}
      custom-field-type: {}
      dn: {}
      email: {}
      limit: {}
      name: {}
      user-account-control-out: {}
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 140,
          "y": 220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: f7734a89-01d4-4796-86be-9c6146b504af
    type: condition
    task:
      id: f7734a89-01d4-4796-86be-9c6146b504af
      version: -1
      name: check
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "18"
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualNumber
          left:
            value:
              complex:
                root: Account
                transformers:
                - operator: count
            iscontext: true
          right:
            value:
              simple: "200"
    view: |-
      {
        "position": {
          "x": 140,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: 902ce9b6-1ad3-4b72-891e-4ed9c5023a49
    type: regular
    task:
      id: 902ce9b6-1ad3-4b72-891e-4ed9c5023a49
      version: -1
      name: Limit is not set currently
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: '"Limit is not set currently" '
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 10,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "19":
    id: "19"
    taskid: d154eda7-7d17-4d3c-8680-225f122792e0
    type: regular
    task:
      id: d154eda7-7d17-4d3c-8680-225f122792e0
      version: -1
      name: Run ad-get-user with limit=2
      description: Retrieves detailed information about a user account. The user can
        be specified by name, email address, or as an Active Directory Distinguished
        Name (DN). If no filter is specified, all users are returned.
      script: '|||ad-get-user'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      attributes: {}
      custom-field-data: {}
      custom-field-type: {}
      dn: {}
      email: {}
      limit:
        simple: "2"
      name: {}
      user-account-control-out: {}
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 780,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "20":
    id: "20"
    taskid: 5f0c71e9-6949-4617-8e2d-7afbf09fb810
    type: condition
    task:
      id: 5f0c71e9-6949-4617-8e2d-7afbf09fb810
      version: -1
      name: check
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "18"
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualNumber
          left:
            value:
              complex:
                root: Account
                transformers:
                - operator: count
            iscontext: true
          right:
            value:
              simple: "2"
    view: |-
      {
        "position": {
          "x": 780,
          "y": 440
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "21":
    id: "21"
    taskid: df8a85be-2e54-4343-88f3-56f6cd9d1701
    type: regular
    task:
      id: df8a85be-2e54-4343-88f3-56f6cd9d1701
      version: -1
      name: Delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 440,
          "y": -230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1295,
        "width": 1150,
        "x": 10,
        "y": -380
      }
    }
  }
inputs:
- key: Username
  value: {}
  required: false
  description: Search for user by the sAMAccountName attribute in Active Directory.
  playbookInputQuery: null
- key: UserEmail
  value:
    complex:
      root: Account
      accessor: Email
      transformers:
      - operator: uniq
  required: false
  description: Search for user by the email attribute in Active Directory.
  playbookInputQuery: null
outputs:
- contextPath: UserManagerEmail
  description: The email of the user's manager.
- contextPath: UserManagerDisplayName
  description: The display name of the user's manager.
  type: unknown
sourceplaybookid: Active Directory - Get User Manager Details
